const FIELDS = [
  ['creditDebit', 'Credit / debit', 'Signed amount'], ['cash', 'Cash', 'Käteinen'],
  ['register', 'Cash register', 'Kassa'], ['rent40', 'VAT 24% · Rent 40%', 'Alv 24 % Vuokra 40%'],
  ['rent25', 'VAT 24% · Rent 25%', 'Alv 24 % Vuokra 25%'], ['sales5', 'Product sales 5%', 'Tuotemyynti 5%']
];
const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];
let state, saveTimer;
const $ = selector => document.querySelector(selector);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid = () => crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).slice(2);
const periodKey = () => `${state.year}-${String(state.activeMonth).padStart(2, '0')}`;
const rows = () => state.entries[periodKey()] || [];
const number = value => value === '' || value == null || !Number.isFinite(Number(String(value).replace(',', '.'))) ? null : Number(String(value).replace(',', '.'));
const money = value => `${Number(value || 0).toLocaleString('fi-FI', {minimumFractionDigits:2, maximumFractionDigits:2})} €`;
const blank = () => ({ id: uid(), date: new Date().toISOString().slice(0, 10), creditDebit:'', cash:'', register:'', rent40:'', rent25:'', sales5:'' });
function validate(row) { const result=[]; if (!row.date) result.push('Date is required'); FIELDS.forEach(([field,label]) => { if (number(row[field]) === null) result.push(`${label} must be a number`); }); return result; }
function totals() { return FIELDS.reduce((out,[field]) => { out[field]=rows().reduce((sum,row)=>sum+(number(row[field])||0),0); return out; },{}); }
async function api(method, body) { const response=await fetch('/api/accounting/state',{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}); if(!response.ok) throw Error('Database request failed'); return response.json(); }
async function save() { state.audit=state.audit||[]; await api('POST',state); render(); }
function queueSave() { clearTimeout(saveTimer); saveTimer=setTimeout(()=>save().catch(()=>{}),350); }
function shell(content, view='transactions') { const org=state.org; return `<div class="org-app"><aside class="sidebar"><div class="brand"><span class="brand-mark">L</span><div><strong>LedgerOS</strong><small>Organization finance</small></div></div><button class="org-switcher" data-action="org"><span class="org-avatar">NS</span><span><b>${esc(org.name)}</b><small>${esc(org.id)}</small></span><span class="chevron">⌄</span></button><nav class="main-nav"><button class="${view==='transactions'?'active':''}" data-view="transactions"><span>▦</span> Transactions</button><button class="${view==='new'?'active':''}" data-view="new"><span>＋</span> New transaction</button><button class="${view==='review'?'active':''}" data-view="review"><span>✓</span> Review & sign-off</button><button class="${view==='audit'?'active':''}" data-view="audit"><span>◷</span> Audit trail</button></nav><div class="sidebar-bottom"><div class="secure-note"><span>●</span><div><b>Local secure workspace</b><small>SQLite database on this machine</small></div></div><button class="plain-link" data-action="org">Organization settings</button></div></aside><main class="main-content"><header class="topbar"><div><p class="kicker">${esc(org.id)} <span>/</span> Fiscal year ${state.year}</p><h1>${view==='transactions'?'Transactions':view==='new'?'New transaction':view==='review'?'Review & sign-off':'Audit trail'}</h1></div><div class="top-actions"><span class="saved"><i></i> Database saved</span><button class="icon-button" data-action="theme">◐</button><button class="user-button">Finance team <span>⌄</span></button></div></header>${content}<footer class="footer"><span>LedgerOS · ${esc(org.name)} · local SQLite accounting</span><div><button data-action="export">Export backup</button><label><input id="import-file" type="file" accept="application/json,.json">Import JSON</label><button data-action="reset">Reset workspace</button></div></footer></main></div>`; }
function periodBar() { return `<section class="period-bar"><div class="period-title"><span class="period-icon">▣</span><div><b>Fiscal period</b><small>All entries are grouped by month</small></div></div><select id="year">${[state.year-1,state.year,state.year+1].map(y=>`<option ${y===state.year?'selected':''}>${y}</option>`).join('')}</select><div class="month-pills">${MONTHS.map((m,i)=>`<button class="${state.activeMonth===i+1?'active':''}" data-month="${i+1}">${m.slice(0,3)}</button>`).join('')}</div></section>`; }
function tabBar(active) { return `<div class="workspace-tabs"><button class="${active==='transactions'?'active':''}" data-view="transactions">All transactions <span>${rows().length}</span></button><button class="${active==='new'?'active':''}" data-view="new">＋ New transaction</button><button class="${active==='review'?'active':''}" data-view="review">Review & sign-off</button></div>`; }
function transactions() { const list=rows(), t=totals(), bad=list.filter(row=>validate(row).length).length; return shell(`${periodBar()}${tabBar('transactions')}<section class="metrics"><div class="metric accent"><small>Period total</small><strong>${money(Object.values(t).reduce((a,b)=>a+b,0))}</strong><span>${list.length-bad} verified entries</span></div><div class="metric"><small>Cash movement</small><strong>${money(t.cash)}</strong><span>Cash + register</span></div><div class="metric"><small>VAT tracked</small><strong>${money(t.rent40+t.rent25)}</strong><span>24% rental accounts</span></div><div class="metric ${bad?'warning':'success'}"><small>Verification</small><strong>${list.length?Math.round((list.length-bad)/list.length*100):100}%</strong><span>${bad?`${bad} need attention`:'Ready for review'}</span></div></section><section class="workspace-head"><div><p class="kicker">${MONTHS[state.activeMonth-1]} ${state.year}</p><h2>Transaction register</h2><p class="muted">View and manage saved transactions for this fiscal period.</p></div><div class="head-actions"><button class="secondary" data-action="import">Import backup</button><button class="primary" data-view="new">＋ New transaction</button></div></section><section class="register-card"><div class="card-toolbar"><div class="toolbar-status"><span class="status-dot ${bad?'warning':''}"></span><b>${bad?`${bad} entries need attention`:'All entries verified'}</b><span class="muted">· ${list.length} total</span></div></div><div class="table-wrap"><table><thead><tr><th>Check</th><th>Date</th>${FIELDS.map(([,label,hint])=>`<th>${label}<small>${hint}</small></th>`).join('')}<th></th></tr></thead><tbody>${list.length?list.map(rowHtml).join(''):'<tr><td colspan="9" class="empty">No transactions recorded for this period.<br><button class="primary" data-view="new" style="margin-top:14px">＋ Create first transaction</button></td></tr>'}</tbody><tfoot><tr><td colspan="2"><b>Period totals</b></td>${FIELDS.map(([field])=>`<td><b>${money(t[field])}</b></td>`).join('')}<td></td></tr></tfoot></table></div><div class="table-foot"><span>Transactions are verified when they are created.</span><button class="text-button" data-view="new">＋ Create another transaction</button></div></section>`,'transactions'); }
function rowHtml(row) { const bad=validate(row).length; return `<tr class="${bad?'needs-review':''}"><td><span class="row-check ${bad?'bad':''}" title="${esc(validate(row).join('. '))}">${bad?'!':'✓'}</span></td><td>${esc(row.date)}</td>${FIELDS.map(([field])=>`<td>${money(row[field])}</td>`).join('')}<td><button class="delete-button" data-remove="${row.id}" title="Delete transaction">×</button></td></tr>`; }
function newTransaction() { const draft=state.draft||blank(); const problems=validate(draft); return shell(`${periodBar()}${tabBar('new')}<section class="form-page"><div class="form-intro"><p class="kicker">Create and verify</p><h2>New transaction</h2><p class="muted">Complete all workbook fields. The transaction can only be saved after every detail passes validation.</p></div><form id="transaction-form" class="transaction-form"><div class="form-grid"><label>Date <span>required</span><input data-draft="date" type="date" value="${esc(draft.date)}"></label>${FIELDS.map(([field,label,hint])=>`<label>${label} <span>required</span><small>${hint}</small><input data-draft="${field}" inputmode="decimal" placeholder="0.00" value="${esc(draft[field])}"></label>`).join('')}</div><div class="verification-box ${problems.length?'has-errors':'verified'}"><div class="verification-icon">${problems.length?'!':'✓'}</div><div><b>${problems.length?`${problems.length} details need attention`:'Transaction details verified'}</b><small>${problems.length?problems.join(' · '):'All required fields are present and numeric. Ready to save.'}</small></div></div><div class="form-actions"><button type="button" class="secondary" data-view="transactions">Cancel</button><button type="submit" class="primary" ${problems.length?'disabled':''}>Save verified transaction</button></div></form></section>`,'new'); }
function review() { const list=rows(), bad=list.filter(r=>validate(r).length), signed=state.signOffs?.[periodKey()]; return shell(`${periodBar()}${tabBar('review')}<section class="review-page"><section class="review-hero"><div><p class="kicker">Control center</p><h2>${MONTHS[state.activeMonth-1]} ${state.year} review</h2><p class="muted">Verify the period, then record an accountable manager sign-off.</p></div><div class="readiness ${bad.length?'warning':signed?'ready':'warning'}"><strong>${bad.length?'Action required':signed?'Signed off':'Ready for manager'}</strong><span>${bad.length?`${bad.length} incomplete entries`:signed?`Signed by ${esc(signed.manager)}`:`${list.length} entries verified`}</span></div></section><div class="checklist"><div class="check-item ${list.length?'done':''}"><span class="check-icon">${list.length?'✓':'!'}</span><div><b>Transactions recorded</b><small>${list.length} transaction rows found</small></div><span class="check-label">${list.length?'Complete':'Needs attention'}</span></div><div class="check-item ${list.length&&!bad.length?'done':''}"><span class="check-icon">${list.length&&!bad.length?'✓':'!'}</span><div><b>All workbook fields verified</b><small>${bad.length?'Date and six numeric fields are required on every row':'Every saved transaction passes field validation'}</small></div><span class="check-label">${list.length&&!bad.length?'Complete':'Needs attention'}</span></div><div class="check-item ${signed?'done':''}"><span class="check-icon">${signed?'✓':'—'}</span><div><b>Manager sign-off</b><small>${signed?`Signed by ${esc(signed.manager)} on ${new Date(signed.time).toLocaleString('en-GB')}`:'A manager must confirm this period is ready'}</small></div><span class="check-label">${signed?'Complete':'Pending'}</span></div></div>${!signed?`<form id="signoff-form" class="signoff-card"><div><p class="kicker">Approval action</p><h3>Record manager sign-off</h3><p class="muted">This records who reviewed the current period and when.</p></div><div class="signoff-controls"><input id="manager-name" placeholder="Manager name" required><button class="primary" type="submit" ${bad.length||!list.length?'disabled':''}>Sign off period</button></div></form>`:`<div class="signed-card"><b>Period signed off by ${esc(signed.manager)}</b><button class="secondary" data-action="unsign">Remove sign-off</button></div>`}</section>`,'review'); }
function audit() { return shell(`<section class="audit-page"><div class="workspace-head"><div><p class="kicker">Local activity log</p><h2>Audit trail</h2><p class="muted">A chronological record of workspace actions for operational accountability.</p></div></div><div class="audit-list">${(state.audit||[]).slice().reverse().map(item=>`<div class="audit-row"><span class="audit-icon">◷</span><div><b>${esc(item.action)}</b><small>${new Date(item.time).toLocaleString('en-GB')}</small></div><span class="audit-source">Finance team</span></div>`).join('')}</div></section>`,'audit'); }
function render(view=window.currentView||'transactions') { window.currentView=view; document.querySelector('#root').innerHTML=view==='transactions'?transactions():view==='new'?newTransaction():view==='review'?review():audit(); }
async function addDraft() { const draft=state.draft||blank(), problems=validate(draft); if(problems.length)return; const k=periodKey(); state.entries[k]=[...(state.entries[k]||[]), {...draft,id:uid()}]; delete state.draft; state.audit.push({id:uid(),action:`Verified transaction added to ${MONTHS[state.activeMonth-1]}`,time:new Date().toISOString()}); await save(); }
function modal(type) { const body=type==='org'?`<div class="modal-head"><div><p class="kicker">Organization profile</p><h2>Workspace settings</h2></div><button data-close>×</button></div><label>Organization name<input id="org-name" value="${esc(state.org.name)}"></label><label>Organization ID<input id="org-id" value="${esc(state.org.id)}"></label><label>Reporting currency<select id="org-currency"><option>EUR</option><option>USD</option><option>SEK</option></select></label><div class="modal-actions"><button class="secondary" data-close>Cancel</button><button class="primary" data-save-org>Save settings</button></div>`:`<div class="modal-head"><div><p class="kicker">Data portability</p><h2>Import organization backup</h2></div><button data-close>×</button></div><p class="muted">Import replaces the current SQLite workspace. Export a backup first if needed.</p><label class="dropzone">Choose a LedgerOS JSON file<input id="modal-file" type="file" accept="application/json,.json"></label>`; document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop"><div class="modal">${body}</div></div>`); }
document.addEventListener('click',async e=>{const view=e.target.closest('[data-view]');if(view){if(view.dataset.view==='new')state.draft=state.draft||blank();return render(view.dataset.view);}const action=e.target.closest('[data-action]')?.dataset.action;if(action==='org')return modal('org');if(action==='import')return modal('import');if(action==='theme'){document.documentElement.setAttribute('data-theme',document.documentElement.getAttribute('data-theme')==='dark'?'light':'dark');return;}if(action==='export'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`ledgeros-${state.year}.json`;a.click();return;}if(action==='reset'&&confirm('Reset this organization workspace?')){location.href=location.pathname+'?reset=1';return;}if(action==='unsign'){delete state.signOffs[periodKey()];state.audit.push({id:uid(),action:'Manager sign-off removed',time:new Date().toISOString()});return save();}const month=e.target.closest('[data-month]');if(month){state.activeMonth=Number(month.dataset.month);return save();}if(e.target.matches('[data-close]')||e.target.closest('[data-close]'))return e.target.closest('.modal-backdrop').remove();if(e.target.matches('[data-save-org]')){state.org.name=$('#org-name').value;state.org.id=$('#org-id').value;state.org.currency=$('#org-currency').value;state.audit.push({id:uid(),action:'Organization settings updated',time:new Date().toISOString()});document.querySelector('.modal-backdrop').remove();return save();}const remove=e.target.closest('[data-remove]');if(remove&&confirm('Remove this transaction?')){state.entries[periodKey()]=rows().filter(r=>r.id!==remove.dataset.remove);state.audit.push({id:uid(),action:'Transaction removed',time:new Date().toISOString()});return save();}});
document.addEventListener('change',async e=>{if(e.target.id==='year'){state.year=Number(e.target.value);return save();}if(e.target.id==='import-file'||e.target.id==='modal-file'){const file=e.target.files[0];if(!file)return;try{const incoming=JSON.parse(await file.text());if(!incoming.org||!incoming.entries)throw Error();state=incoming;document.querySelector('.modal-backdrop')?.remove();await save();}catch{alert('Import rejected. Use a LedgerOS JSON export.');}}});
document.addEventListener('input',e=>{const field=e.target.dataset.draft;if(!field)return;state.draft=state.draft||blank();state.draft[field]=e.target.value;queueSave();render('new');const fresh=document.querySelector(`[data-draft="${field}"]`);fresh?.focus();fresh?.setSelectionRange(fresh.value.length,fresh.value.length);});
document.addEventListener('submit',async e=>{e.preventDefault();if(e.target.id==='transaction-form')return addDraft();if(e.target.id==='signoff-form'){const manager=$('#manager-name').value.trim();if(!manager||rows().some(r=>validate(r).length))return;state.signOffs=state.signOffs||{};state.signOffs[periodKey()]={manager,time:new Date().toISOString()};state.audit.push({id:uid(),action:`${manager} signed off ${MONTHS[state.activeMonth-1]} ${state.year}`,time:new Date().toISOString()});return save();}});
(async()=>{try{state=await api('GET');state.signOffs=state.signOffs||{};if(new URLSearchParams(location.search).has('reset')){state={org:{name:'Northstar Cooperative',id:'FI-ORG-001',currency:'EUR'},year:new Date().getFullYear(),activeMonth:new Date().getMonth()+1,entries:{},signOffs:{},audit:[{id:uid(),action:'Workspace reset',time:new Date().toISOString()}]};await save();}render();}catch{document.querySelector('#root').innerHTML='<div class="empty" style="padding:80px">Unable to open the local accounting database. Start the app with <code>python3 server.py</code>.</div>';}})();
